title: "Javier Urbina"
#description: "Biomedical Engineering Portfolio"
theme: minima

# Navigation menu
nav:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Projects"
    link: "/projects"
  - name: "CV"
    link: "/cv.pdf"
